### ISSUE TITLE
Info2 in plant picker reporting incorrect info

### ISSUE THREAD

**Issue by guilevi** [CG8516/PvZA11y#14]
In adventure levels 2/2 and 2/3, pressing info2 reports "day", though they are actually night levels ([Source](https://plantsvszombies.fandom.com/wiki/Level_2-2)).

**Comment by CG8516** [comment]
Hey, thanks for the report!  
Just patched the code, will be fixed in the next update.

**Comment by Cyrax2001** [comment]
Talking about the info 2 button, it would be great if its purpose changed within the gameplay. Previously, verbalizing the element in the current tile was necessary because the mod didn't do it automatically. However, now that reading the element is automatic, we could say it is irrelevant.
I propose something else: that the info 2 button serves to determine how many waves of zombies there will be in the game or how many have been surpassed. As far as I know, this is something visually displayed for sighted players.
This way, in levels with 3 waves, it could be something like: "Wave 1 of 3," "Wave 2 of 3," "Wave 3 of 3."
Yes, I'm aware that info 4 informs both about progress and the wave... There's something I'd like to ask. Could you make the same information button behave differently if pressed twice? For example, if info 2 can't be used as I propose, could you make it so that quickly pressing info 4 twice tells you the wave progress instead of the level progress as a percentage?

**Comment by CG8516** [comment]
Having the plant/object information read automatically is a user choice, and can be turned off.  
Info2 might be irrelevant for some users, but others may prefer to only read the plant information when they press the button, so they can navigate the board without it interrupting the zombie sonar.  

Funnily enough, wave progress is something I added literally while you were making that comment.  
The way I added, Info4 will say something like: "37%, wave 1 of 3"  
Is that fine, or would you prefer a double-tap to read just the wave number?

**Comment by Cyrax2001** [comment]
How do you manage to be so efficient? You scare me! Maybe the double press on info 4 isn't necessary. Perhaps it's something you could implement later. Maybe the double press feature could be better utilized in other accessibility elements.
Maybe not now, but it would be interesting to try out how it would work if, by quickly pressing the slot buttons twice, the amount of sun required for their use could be read, without having to hear the name of the plant first.
Maybe this sounds strange to you, but many blind individuals like to do things as quickly as possible and acquire important information as fast as they can. For example, when you made the elements in the tiles read automatically, you made them read before the coordinate of that tile. It could have easily been something like "a1 sunflower," but that would slow things down for us. By reading it backward, you allow the relevant information to be vocalized first: "sunflower a1."
By the way, thank you very much for doing so.

**Comment by CG8516** [comment]
Haha, it was just good timing.  
The next update will have the double-tap actions for info4 and plant slots. Maybe some of the other inputs would benefit from this too.

And that doesn't sound strange at all. It was something I also wanted, after trying to complete adventure mode without any visuals. Relaying important information as efficiently as possible is one of the project's core goals.

**Comment by guilevi** [comment]
Thanks a lot for the quick response! I actually really like how information is structured and relayed. It takes some getting used to but I find it seriously efficient.

**Comment by CG8516** [comment]
Beta 1.13 fixes the Info2 day/night info, includes wave progress, and allows you to double-tap slot hotkeys and info4 to skip narration ahead.
