### ISSUE TITLE
It's still a matter of language. 

### ISSUE THREAD

**Issue by piano777wzy** [CG8516/PvZA11y#40]
It's still a matter of language.
Hello, there is a new problem, there are some basic items can not be translated, such as pressing the exc hotkey during the game to open the option menu options can not be translated, there are other places.
There are also some of the internal text of the game, there is no way to translate, there are no these entries.

**Comment by Cyrax2001** [comment]
The user is referring to the fact that, for example, when a sun is automatically collected, it is not possible to translate the word "sun" to Spanish. It is also not possible to translate the entire section for reassigning inputs, nor some dialogues, like the one used to delete games, nor the interface for creating new games. Also, some minor things here and there. Since I am using the Spanish version of the game, it is something I have encountered a lot while translating it. Speaking of that, I finished my translation. There is still that problem and the issue presented in the issue #37 , but I would love it if, when everything is completed, it could be officially included in the mod.

**Comment by CG8516** [comment]
The input rebinding is a huge one, no idea how I missed that one, sorry.  
All of the username dialogues use text from the game's memory, so they might be missing from the translation mod you're using.  
The next update, 1.16, will have the input rebind menu and a few other changes, which will require some adjustments to your translation files. There will be more detailed instructions at the bottom of the release notes.

**Comment by CG8516** [comment]
Translations have now been updated in [Beta 1.16](https://github.com/CG8516/PvZA11y/releases/tag/beta.1.16)
